# Generated by Django 5.1.2 on 2024-11-07 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pet',
            new_name='Watch',
        ),
    ]
